kind: Service
apiVersion: v1
metadata:
  name: spark-thrift-server-service
  namespace: emr
spec:
  type: LoadBalancer
  selector:
    app: spark-thrift-server-driver
  ports:
    - name: jdbc-port
      protocol: TCP
      port: 10001
      targetPort: 10001
